data_warehouse:
  target: dev
  outputs:
    dev:
      dataset: dbt_commandline_central_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/nxtwave/Downloads/project-on-dbt-379106-829d80980b39.json
      location: asia-south1
      method: service-account
      priority: interactive
      project: project-on-dbt-379106
      threads: 4
      type: bigquery

data_warehouse_2:
  target: dev
  ##test details

